selected_tool = None
start_pos = {"x": 0, "y": 0}
scale = 1.0
selected_point = None
current_pen = None
current_polyline = None
label_counter = 0
lower_label_counter = 0
label_unused = []
lower_label_unused = []
points_for_obj = []
freehand_last_pos = {"x": 0, "y": 0}
drag_target = None
deleted_point_label = None
center = (0, 0)
sidebar_width = 0
sidebar_resizing = False
