name: Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            suffix: -linux
            ext: ''
          - os: macos-latest
            suffix: -darwin
            ext: ''
          - os: windows-latest
            suffix: -windows
            ext: '.exe'
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Create .env file from secrets
        run: |
          echo "API_AUDIENCE=${{ secrets.API_AUDIENCE }}" > .env
          echo "AUTH0_CALLBACK_URL=${{ secrets.AUTH0_CALLBACK_URL }}" >> .env
          echo "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" >> .env
          echo "AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}" >> .env
          echo "AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" >> .env
          echo "TURSO_AUTH_TOKEN=${{ secrets.TURSO_AUTH_TOKEN }}" >> .env
          echo "TURSO_URL=${{ secrets.TURSO_URL }}" >> .env

      - name: build
        run: |
          python -m PyInstaller --onefile --noconsole --noconfirm --hidden-import struct --hidden-import _struct --add-data "locales${{ runner.os == 'Windows' && ';' || ':' }}locales" --name py-geogebra${{ matrix.suffix }} --add-data "resources:resources" --hidden-import=requests --hidden-import=dotenv --hidden-import=libsql_client --hidden-import=requests --hidden-import=flask --hidden-import=threading --add-data ".env:." --add-data "py_geogebra/flask/templates:py_geogebra/flask/templates" --add-data "py_geogebra/flask/static:py_geogebra/flask/static" main.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: py-geogebra${{ matrix.suffix }}
          path: dist/py-geogebra${{ matrix.suffix }}${{ matrix.ext }}
          if-no-files-found: error


  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Get mf files
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Read version
        run: |
          echo "version=$(python -c 'import py_geogebra.config as v; print(v.__version__)')" >> $GITHUB_ENV

      - name: Chmod it
        run: chmod +x dist/**/py-geogebra*-linux dist/**/py-geogebra*-darwin || true

      - name: Create tars
        run: |
          for f in dist/**/py-geogebra*-linux dist/**/py-geogebra*-darwin; do
            [ -f "$f" ] && tar -czf "$f.tar.gz" -C "$(dirname "$f")" "$(basename "$f")"
          done

      - name: Upload to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.version }}
          name: "PyGeoGebra v${{ env.version }}"
          make_latest: true
          files: |
            dist/**/py-geogebra*-windows.exe
            dist/**/py-geogebra*-darwin.tar.gz
            dist/**/py-geogebra*-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


