name: Build and Release

on:
  push:
    tags:
      - 'v*'     # runs on version tags

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build 
        run: |
          python -m PyInstaller --onefile --noconsole --noconfirm --add-data "locales:locales" main.py

      - name: Upload 
        uses: softprops/action-gh-release@v2
        with:
          files: dist/py-geogebra
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
