name: Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Deps ktore boli cachnute
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build
        run: |
          python -m PyInstaller --onefile --noconsole --noconfirm \
            --add-data "locales${{ runner.os == 'windows-latest' && ';' || ':' }}locales" \
            --name py-geogebra main.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: py-geogebra-${{ matrix.os }}
          path: |
            dist/py-geogebra${{ matrix.os == 'windows-latest' && '.exe' || '' }}
