name: Build and Release

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build 
        run: |
          python -m PyInstaller --onefile --noconsole --noconfirm --add-data "locales:locales" main.py

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: py-geogebra
          path: dist/py-geogebra

