name: Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Deps ktore boli cachnute
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build
        run: |
          python -m PyInstaller --onefile --noconsole --noconfirm --add-data "locales${{ runner.os == 'windows-latest' && ';' || ':' }}locales" --name py-geogebra main.py

      - name: Read version
        id: get_version
        run: |
          echo "version=$(python -c 'import py_geogebra.version as v; print(v.__version__)')" >> $GITHUB_ENV

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.version }}
          make_latest: true
          name: "PyGeoGebra v${{ env.version }}"
          files: dist/py-geogebra${{ matrix.os == 'windows-latest' && '.exe' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
